const ACCESSTOKEN_EXP_ERROR = require('./ACCESSTOKEN_EXP_ERROR');
const REFRESHTOKEN_EXP_ERROR = require('./REFRESHTOKEN_EXP_ERROR');
const UNAUTH_USER = require('./UNAUTH_USER');
const SYSTEMTOKEN_EXP_ERROR = require('./SYSTEMTOKEN_EXP_ERROR');

module.exports = {
  ACCESSTOKEN_EXP_ERROR,
  REFRESHTOKEN_EXP_ERROR,
  SYSTEMTOKEN_EXP_ERROR,
  UNAUTH_USER,
};
