const MS_SERVER_ERROR = require('./MS_SERVER_ERROR');
const OTP_SERVER_ERROR = require('./OTP_SERVER_ERROR');
const RMS_SERVER_ERROR = require('./RMS_SERVER_ERROR');
const UMS_SERVER_ERROR = require('./UMS_SERVER_ERROR');
const HH_SERVER_ERROR = require('./HH_SERVER_ERROR');
const EMS_SERVER_ERROR = require('./EMS_SERVER_ERROR');
const CMS_SERVER_ERROR = require('./CMS_SERVER_ERROR');

module.exports = {
  MS_SERVER_ERROR,
  OTP_SERVER_ERROR,
  RMS_SERVER_ERROR,
  UMS_SERVER_ERROR,
  HH_SERVER_ERROR,
  EMS_SERVER_ERROR,
  CMS_SERVER_ERROR,
};
